# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Pelumi Aboluwarin
tagline:             Random musings on tech, entrepreneurship and life
url:                 http://pelumi.maven.ai
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Pelumi Aboluwarin
  url:               https://twitter.com/pelumiy
  email:             pelumi[at]maven.ai

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/poole/poole

pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'